//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaVideotheque
{
    using System;
    using System.Collections.Generic;
    
    public partial class Location
    {
        public System.Guid id { get; set; }
        public System.Guid id_client { get; set; }
        public long id_film { get; set; }
        public bool rendu { get; set; }
        public System.DateTime date_debut { get; set; }
        public System.DateTime date_fin { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Film Film { get; set; }
    }
}
